spring.application.name=bookmyshow_service

spring.jpa.hibernate.ddl-auto=update
#for local postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyshow
spring.datasource.username=postgres
spring.datasource.password=Abcd@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql= true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


#For docker container
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER}
#spring.jpa.show-sql= ${SPRING_JPA_SHOW_SQL}

spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.idleTimeout=10000


stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
STRIPE_WEBHOOK_SECRET=whsec_OldL5zfGsT91jyYRMVLeFyAq4ZlSWEIm