spring.application.name=bookmyshow_service

spring.jpa.hibernate.ddl-auto=update
#for local postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyshow
#For docker container
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER}
spring.jpa.show-sql= ${SPRING_JPA_SHOW_SQL}

spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.idleTimeout=10000